name: Build Pipeline on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted   # Run the job on your self-hosted runner (Ubuntu)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t python-ubuntu-test .

      - name: Run Docker container
        run: docker run python-ubuntu-test bash -c "echo Container runs successfully on self-hosted Ubuntu runner"
