name: Build and Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t python-ubuntu-test .
      - name: Run tests (or any other pipeline step)
        run: docker run python-ubuntu-test
